image: sikalabs/ci

stages:
  - lint
  - build-js
  - build-docker
  - deploy-dev
  - deploy-dev-check
  - deploy-prod
  - deploy-prod-check

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .yarn-cache .next .kaniko-cache

eslint:
  image: node:16-slim
  stage: lint
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
    - yarn run lint

prettier:
  image: node:16-slim
  stage: lint
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
    - yarn run prettier-check

build js:
  image: node:16-slim
  stage: build-js
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
    - yarn run build
  artifacts:
    paths:
      - out
    expire_in: 1 week

build docker:
  stage: build-docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context .
      --dockerfile ./Dockerfile
      --destination $CI_REGISTRY_IMAGE
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
      --cache=true
      --cache-dir .kaniko-cache
      --cache-repo $CI_REGISTRY_IMAGE/cache

.dev:
  rules:
    - if: $CI_COMMIT_BRANCH

.prod:
  rules:
    - if: $CI_COMMIT_TAG

.deploy:
  script:
    - helm upgrade --install $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
      one-image --repo https://helm.sikalabs.io
      --namespace $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
      --create-namespace
      --set image=$IMAGE
      --set host=$HOST
    - slu wait-for tls -a $HOST:443

deploy dev:
  stage: deploy-dev
  extends:
    - .deploy
    - .dev
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_DOMAIN
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_DOMAIN
    on_stop: stop dev

stop dev:
  stage: deploy-dev
  extends:
    - .dev
  when: manual
  variables:
    GIT_STRATEGY: none
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop
  script:
    - helm uninstall $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
      --namespace $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG

deploy dev check:
  extends:
    - .dev
  stage: deploy-dev-check
  script:
    - curl https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_DOMAIN

deploy prod:
  stage: deploy-prod
  extends:
    - .deploy
    - .prod
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    HOST: $BASE_DOMAIN
  environment:
    name: prod
    url: https://$BASE_DOMAIN

deploy prod check:
  extends:
    - .prod
  stage: deploy-prod-check
  script:
    - curl https://$BASE_DOMAIN
